config/routes.rb
ArtHouse::Application.routes.draw do
  resources :accounts do
    get :delete, :on => :member
    get :updater, :on => :member

    collection do
      get 'updater'
      get 'makeadmin'
      get 'makesuper'
      get 'list'
      get 'login'
      get 'logout'
      get 'permission'
      get 'changepassword'
    end
  end

  resources :events do
        get :delete, :on => :member
      end

  resources :works do
    get :delete, :on => :member
    collection do
      get 'show_artist'
    end
  end
  match "/works/show_artist/:id" => "works#show_artist"
  root :to => 'pages#about'
  resources :artists do
    get :delete, :on => :member
    collection do
    get :alumni
      end
  end
  get "pages/about"

  get "pages/contact"

  get "pages/bios"

  get "pages/gallery"

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  
  has_many :works
  has_attached_file :photo
  validates_presence_of :name, :bio, :sizex, :sizey, :stillthere
  validates_numericality_of :stillthere
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :auth, :except => [:show,:index, :alumni]
  before_filter :set_env
  def index
    @artists = Artist.find(:all, :order => 'name')
    @currentartists = @artists.find_all {|item| item.stillthere==1}
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @artists }
    end
  end

  def alumni
    @artists = Artist.find(:all, :order => 'name')
    @alumni = @artists.find_all {|item| item.stillthere==0}
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @artists }
    end
  end
  def show
    @artist = Artist.find(params[:id])
    @imgtag = ""
    if @artist.photo_file_name.nil?
        @imgtag = "NoImg.jpg"
    else
      @imgtag = @artist.photo.url
    end
    @sizex = @artist.sizex
    @sizey = @artist.sizey


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @artist }
    end
  end

  def new
    if authenticate("creation")
    @artist = Artist.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @artist }
    end
    else
      permalt
    end
  end

  def edit
    if authenticate("priviledged")
    @artist = Artist.find(params[:id])
    else
      permalt
    end
  end

  def create
    account = authenticate("creation")
    if account
    @artist = Artist.new(params[:artist])


    respond_to do |format|
      if @artist.save
        

        # update account to reflect created artist
        if account.permission == -2
          account.update_attribute(:permission, 1)
          account.update_attribute(:artist, @artist.id)
        elsif account.permission == -1
          account.update_attribute(:permission, 0)
          account.update_attribute(:artist, @artist.id)
        end


        format.html { redirect_to(@artist, :notice => 'Artist was successfully created.') }
        format.xml  { render :xml => @artist, :status => :created, :location => @artist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
      end
    end
    else
      permalt
    end
  end

  def update
        if authenticate("priviledged")
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to(@artist, :notice => 'Artist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
      end
    end
    else
          permalt
    end
  end

  def destroy
    if authenticate("priviledged")

    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to(artists_url) }
    end
    else
      permalt
    end
  end
  
  def delete
        if authenticate("priviledged")

        else
          permalt
        end
  end
  
  def set_env
    @banner = "banner.jpg"
  end
  protected
  
  # def authenticate
  #   authenticate_or_request_with_http_basic do |user, password|
  #     for i in 1..1000 do
  #       password = Digest::SHA256.hexdigest(password)
  #     end
  #     if !(user == "admin" && password == "6a631dd57fc7f184b1e92a5ddea94076d1fb4c05341816201ce0454d79a04562")
  #       redirect_to(artists_path, :notice => "Sorry. You can't do that.")          
  #     else
  #       true
  #     end 
  #   end
  # end


    def permalt
        respond_to do |format|
          format.html { render(:controller => 'accounts', :action => "permission") }
        end
    end


    def permissions(act, account)
      @permission = account.permission
      if @permission.nil?
        false
      else
        artist = account.artist
        case act
        when "login"
          true
        when "priviledged" # is admin or artist
            if admin?(@permission)
              true
            elsif account.artist == params[:id].to_i
              true
            else
              false
            end
        when "creation" #admin or negative artist
          if admin?(@permission)
            account
          elsif neg?(@permission)
            account
          else
            false
          end
        end #case end
        
      end
    end
    def auth
      authenticate("login")
    end
    def authenticate(action)
      @match = nil
      if (session[:username].nil? or session[:passhash].nil?)
        authenticate_or_request_with_http_basic do |user, password|
          @match= Account.find_by_username(user)


          passhash = "xxxxxxxxxx"
          unless @match.nil?
            passhash = Account.encrypt(password, @match.salt)
            if !(@match.hashedpass == passhash)
              @match = nil
            else
              session[:username] = user
              session[:passhash] = passhash
            end
          else
            @match = nil

          end
        end
        # above end authenticate_http
      else
        @match = Account.find_by_username(session[:username])
        unless @match.nil?
        if !(@match.hashedpass == session[:passhash])
          match = nil
        end
          end
      end
      

      if @match.nil?
        false
      else
        if action.nil?
          action= "login"
        end
        permissions(action, @match)
      end


    end

    def su?(permission)
      if permission == 2
        true
      else
        false
      end
    end
    def admin?(permission)
      if permission == 1 or permission == 2
        return true
      else
        return false
      end
    end
    def neg?(permission)
      if permission == -1 or permission == -2
        return true
      else
        return false
      end
    end



end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/.#_form.html.erb
megaloman@ragebox.7992:1314049921

app/views/artists/_form.html.erb
<%= form_for @artist, :html => { :multipart => true } do |f| %>

<% if @artist.errors.any? %>
<h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

<ul>
  <% @artist.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<%= f.label(:photo, "Photo File") %>
<br />
<%= f.file_field :photo %>
<br />
<%= f.label(:name, "Name:") %>
<br />
<%= f.text_field(:name) %>
<br />
<%= f.label(:bio, "Bio:") %>
<br />
<%= f.text_area(:bio) %>
<br />
<%= f.label(:sizex, "Vertical Photo size") %>
<br />
<%= f.text_field(:sizex) %>
<br />
<%= f.label(:sizey, "Horizontal photo size") %>
<br />
<%= f.text_field(:sizey) %>
<br />
<br />
<%= f.label(:stillthere, "Is the artist currently living at the house. 0 for no, 1 for yes.") %>
<br />
<%= f.text_field(:stillthere) %>
<br />
<br />
<%= f.submit("Submit") %> 
<% end %>

app/views/artists/alumni.html.erb
<p id="notice"><%= notice %></p>
      <div id="ArtistList">
<h1>Our Talented Alumni</h1>


<% @alumni.each do |artist| %>
  <br />
    <%= link_to artist.name, artist %>
<% end %>

<br /><br /><br />
<%= link_to "See our current artists.", :controller => :artists, :action => :index %>
</div>

app/views/artists/delete.html.erb
<h1>Deleted Artist</h1>

<% @artist = Artist.find(params[:id])%>
<% @works = @artist.works %>
<% @works.each do |work| %>
<% work.destroy %>
<% end %>
<% @artist.destroy %>
 <%= link_to 'Artists', artists_path %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>
<div id="TextContain">
<%= form_for @artist, :html => { :multipart => true } do |f| %>

  <% if @artist.errors.any? %>
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>
      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>
<%= f.label(:photo, "Photo File") %>
<br />
<%= f.file_field :photo %>
<br />
<%= f.label(:name, "Name:") %>
<br />
<%= f.text_field(:name) %>
<br />
<%= f.label(:bio, "Bio:") %>
<br />

<%= f.text_area(:bio) %>
<br />
<%= f.label(:sizex, "Photo display vertical size") %>
<br />
<%= f.text_field(:sizex) %>
<br />
<%= f.label(:sizey, "Photo display horizontal size") %>
<br />
<%= f.text_field(:sizey) %>
<br />
<br />
<%= f.label(:stillthere, "Is the artist currently living at the house. 0 for no, 1 for yes.") %>
<br />
<%= f.text_field(:stillthere) %>
<br />

<%= f.submit("Submit") %> 
<% end %>
<br /><br />
<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>
</div>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>
      <div id="ArtistList">
<h1>Our Talented Artists</h1>


<% @currentartists.each do |artist| %>
  <br />
    <%= link_to artist.name, artist %>
<% end %>
 
<br /><br /><br />
<%= link_to "See our former members.", :controller => :artists, :action => :alumni %>
</div>

app/views/artists/new.html.erb
<h1>New artist</h1>
<div id="TextContain">
<%= render 'form' %>
</div>
<%= link_to 'Back', artists_path %>

app/views/artists/permission.html.erb
<div id="BodySurround"><h1>You do not have permission. </h1>
</div>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>
<ul id="biolist">
<li class="bioli">
<div id="ArtistPic">

<%= image_tag(@imgtag, :size => "#{@sizey}x#{@sizex}", :border=> 5) %> 
 <!-- <%= image_tag(@imgtag, :size => "375x350", :border=> 5) %> -->
</div>
</li>
<li class="bioli">
<div id="ArtistLeft">	

  <b>Name:</b>
  <%= @artist.name %>

<div id="floater">
<p clear="both", position="relative">
  <b>Bio:&nbsp&nbsp</b>
  <%= @artist.bio.gsub( '\n', "<br \/><br \/>").html_safe %>
<br /><br />
<%= link_to 'Artists', artists_path %> 
<br />
<%= link_to("See their art" , :controller => "works", :action => "show_artist", :id => @artist.id) %>

</p>
</div>
<!-- <%= link_to 'Edit', edit_artist_path(@artist) %> | -->
</div>
</li>
</ul>