config/routes.rb
ArtHouse::Application.routes.draw do
  resources :accounts do
    get :delete, :on => :member
    get :updater, :on => :member

    collection do
      get 'updater'
      get 'makeadmin'
      get 'makesuper'
      get 'list'
      get 'login'
      get 'logout'
      get 'permission'
      get 'changepassword'
    end
  end

  resources :events do
        get :delete, :on => :member
      end

  resources :works do
    get :delete, :on => :member
    collection do
      get 'show_artist'
    end
  end
  match "/works/show_artist/:id" => "works#show_artist"
  root :to => 'pages#about'
  resources :artists do
    get :delete, :on => :member
    collection do
    get :alumni
      end
  end
  get "pages/about"

  get "pages/contact"

  get "pages/bios"

  get "pages/gallery"

end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :artist
  
  # Stuff to do with attached files is below.
  # Image should have attached file and thumbnail that is smaller.

  has_attached_file :photo, :styles =>  {:index => "200x200", :thumb => "100x100"}
  validates_attachment_presence :photo
  validates_attachment_content_type :photo, :content_type=>['image/jpeg', 'image/png', 'image/gif']  
  validates_attachment_size :photo, :less_than=>1.megabyte
  
  validates :sizex, :presence => true, :numericality => { :greater_than => 100, :less_than_or_equal_to => 800}
  validates :sizey, :presence => true, :numericality => { :greater_than => 100, :less_than_or_equal_to => 800}
  validates :name, :presence => true, :length => {:minimum => 1, :maximum => 200}
  validates :artist_id, :numericality => true
  validates_presence_of :artist
  validates :status, :presence => true, :length => {:minimum => 3, :maximum => 200}
  validates :medium, :presence => true, :length => {:minimum => 3, :maximum => 200}
  validates :size, :presence => true, :length => {:minimum => 3, :maximum => 200}
  validates :date, :presence => true, :length => {:minimum => 4, :maximum => 200}  
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  # GET /works
  # GET /works.xml
  before_filter :auth, :except => [:show,:index, :show_artist]
  before_filter :load_artists, :set_env
 def set_env
    @banner = "banner.jpg"
  end
  
  def load_artists
    artistlocal = Artist.find(:all, :select => [:name, :id, :stillthere])
    @artists = artistlocal.find_all{ |item| item.stillthere==1}
  end

  def index
    @works = Work.all
    @workcount = @works.length
    @numperpage = 6
    @numperline = 3
    @locclose = 0
    unless (params[:list])
      @list = "1"
    else
      @list = params[:list]
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @works }
    end
  end

  # GET /works/1
  # GET /works/1.xml
  def show
    @work = Work.find(params[:id])
    # @imgtag = "gallery/" + @work.name + ".jpg"
    # unless FileTest.exists?("#{RAILS_ROOT}/public/images/#{@imgtag}")
    #   @imgtag = "NoImg.jpg"
    # end
    @imgtag = @work.photo.url
    @sizex = @work.sizex
    @sizey = @work.sizey
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @work }
    end
  end
  
  def show_artist
    if params[:id].nil? then
        @works = Work.all
        @artid = nil
      else
        @artist = Artist.find(Integer(params[:id]))
        @works = @artist.works
        @test = 1
        @artid = Integer(params[:id])
    end
      @workcount = @works.length
      print "Workcount #{@workcount}"
      @numperpage = 6
      @numperline = 3
      @locclose = 0
        unless (params[:list])
          @list = "1"
        else
          @list = params[:list]
        end
        respond_to do |format|
          format.html # index.html.erb
          format.xml  { render :xml => @works }
        end
  end

  def new
    account = authenticate("get_account")
    if account.artist > 0
    @account_artist = account.artist
    @work = Work.new
    respond_to do |format|
      format.html # new.html.erb
    end
    else
      permalt
    end
  end

  def edit
    if authenticate("priviledged")
     @work = Work.find(params[:id])
    else
      permadm
    end
  end

  def create
    account = authenticate("get_account")
    if account.artist > 0
    @work = Work.new(params[:work])

    respond_to do |format|
      if @work.save
        format.html { redirect_to(@work, :notice => 'Work was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
    else
      permalt
    end
  end

  def update
    if authenticate("priviledged")
    @work = Work.find(params[:id])
    respond_to do |format|
      if @work.update_attributes(params[:work])
        format.html { redirect_to(@work, :notice => 'Work was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @work.errors, :status => :unprocessable_entity }
      end
    end
    else
      permadm
    end
  end

  def delete
    if authenticate("priviledged")
      
    else
      permadm
    end
  end

  def destroy
    if authenticate("priviledged")
    @work = Work.find(params[:id])
    @work.destroy
    respond_to do |format|
      format.html { redirect_to(works_url) }
      format.xml  { head :ok }
    end
    else
      permalt
    end
  end

  
  protected
#   def self.encrypt(pass, salt)
#     password = pass
#     Digest::SHA256.hexdigest(pass+salt)
#   end  

#   def authenticate
#     authenticate_or_request_with_http_basic do |user, password|
#         for i in 1..1000 do
#           password = Digest::SHA256.hexdigest(password)
#         end
#         #if  !(user == "admin" && password == "bar")
#          if !(user == "admin" && password == "6a631dd57fc7f184b1e92a5ddea94076d1fb4c05341816201ce0454d79a04562")
#           redirect_to(works_path, :notice => "Sorry. You can't do that.")
#         else
#           true
#         end 
#     end
# end




    def permalt
        respond_to do |format|
          format.html { render(:controller => 'accounts', :action => "permission") }
        end
    end
        def permadm
        respond_to do |format|
          format.html { render(:controller => 'accounts', :action => "permadm") }
        end
    end


    def permissions(act, account)
      @permission = account.permission
      if @permission.nil?
        false
      else
        artist = account.artist
        case act
        when "login"
          true
        when "priviledged" # is admin or artist
            if admin?(@permission)
              true
            elsif account.artist == Work.find(params[:id]).artist.id
              true
            else
              false
            end
        when "get_account"
            account
        end #case end
        
      end
    end
    def auth
      authenticate("login")
    end
    def authenticate(action)
      @match = nil
      if (session[:username].nil? or session[:passhash].nil?)
        authenticate_or_request_with_http_basic do |user, password|
          @match= Account.find_by_username(user)


          passhash = "xxxxxxxxxx"
          unless @match.nil?
            passhash = Account.encrypt(password, @match.salt)
            if !(@match.hashedpass == passhash)
              @match = nil
            else
              session[:username] = user
              session[:passhash] = passhash
            end
          else
            @match = nil

          end
        end
        # above end authenticate_http
      else
        @match = Account.find_by_username(session[:username])
        unless @match.nil?
        if !(@match.hashedpass == session[:passhash])
          match = nil
        end
          end
      end
      

      if @match.nil?
        false
      else
        if action.nil?
          action= "login"
        end
        permissions(action, @match)
      end


    end

    def su?(permission)
      if permission == 2
        true
      else
        false
      end
    end
    def admin?(permission)
      if permission == 1 or permission == 2
        return true
      else
        return false
      end
    end
    def neg?(permission)
      if permission == -1 or permission == -2
        return true
      else
        return false
      end
    end



end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/.#_form.html.erb
megaloman@ragebox.2716:1314141082

app/views/works/.#index.html.erb
megaloman@ragebox.2716:1314141082

app/views/works/.#new.html.erb
megaloman@ragebox.3183:1314850345

app/views/works/_editform.html.erb
<%= form_for @work, :html => { :multipart => true } do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.label(:photo, "Photo File") %>
<br />
<%= f.file_field :photo %>
<br />  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :artist_id %>
  </div>
  <div class="field">
    <%= f.label :sizex, "Display size horizontal typically about 375" %><br />
    <%= f.text_field :sizex %>
  </div>
  <div class="field">
    <%= f.label :sizey, "Display size vertical typically about 375"%><br />
    <%= f.text_field :sizey %>
  </div>
  <div class="field">
    <%= f.label :medium %><br />
    <%= f.text_field :medium %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :price, "Price: Dollars" %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label "Seller contact" %><br />
    <%= f.text_field :seller %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/_form.html.erb
<%= form_for @work, :html => { :multipart => true } do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.label(:photo, "Photo File") %>
<br />
<%= f.file_field :photo %>
<br />  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :artist_id, :value => @account_artist %>
  </div>
  <div class="field">
    <%= f.label :sizex, "Display size horizontal typically about 375" %><br />
    <%= f.text_field :sizex %>
  </div>
  <div class="field">
    <%= f.label :sizey, "Display size vertical typically about 375"%><br />
    <%= f.text_field :sizey %>
  </div>
  <div class="field">
    <%= f.label :medium %><br />
    <%= f.text_field :medium %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :price, "Price: Dollars" %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label "Seller contact" %><br />
    <%= f.text_field :seller %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/delete.html.erb
<h1>Deleted Work</h1>

<% @work = Work.find(params[:id])%>
<% @work.destroy %>
 <%= link_to 'Gallery', works_path %>

app/views/works/edit.html.erb
<h1>Editing work</h1>
<div id="ArtistLeft">
<%= render 'editform' %>
</div>
<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<div id="notice"><%= notice %>
  <b/>
</div>

<%if Integer(@list) * @numperpage < @works.length then%>
     <!-- if the expected last work on the page is not past the length of works. -->
     <!-- use it -->
     <%@max = Integer(@list) * @numperpage -1 %>
     
     <%else%>

     <!-- else use the last work in the list -->
     <%@max = (@works.length) -1 %>
     <%end%>

     <!-- set the start point -->
     <% @start = (Integer(@list)-1) * @numperpage%>
     <% unless @max < @start then %>
	<div id="eventslisting">
          <h3 class="top"> Artwork: page 
            <span id="numberOverload"><%= @list%></span>
          </h3>
	  <!-- display a header -->
	  <p class="bottom">
	    <%@count = @workcount / @numperpage + 1%>
            <%unless @count == 1%>
               <%for each in 1..@count%>
                  <%= link_to each, works_path(:list => each) %>
                   <!-- link to all the other pages -->
	       <%end%>
	    <%end%>
          </p>
       </div>
       <!-- end div eventslisting -->

<div class="out">
  <% (@start..@max).each do |index| %>
  <% @offset = index - @start %>
  <% if (@offset  == (@offset / @numperline) * @numperline ) then%>
  <!-- if we reached the number of pics in a row -->
  <% unless @locclose = 1%>
  <% @locclose = 1 %>
  <ul>
  
  <% else%>
  </ul>
  <ul>
    <% end %>
<!-- end unless -->
    <% end%>
<!-- end if  -->
    <li class="outer">
      <table class="nested">
        <tr>
          <td class="inner">
            <% @img = @works[index] %>
            <div class="imageinstance">
	      <span class="photo">
	    <%= link_to image_tag(@img.photo.url(:index)), @img %>
	    </span>
    <div id="tagger">        <%= @works[index].name %>
    <br/>by
    <% @linkname= @works[index].artist.name%>
    <% @linkpath = @works[index].artist %>
    <%= link_to @linkname, @linkpath%>
</div>
<!-- tagger -->
</div> 
<!-- imageinstance -->
</td>
<!-- class inner -->
</tr>
<!-- inner row -->
</table>
<!-- inner table -->
</li>

<% end %>
</ul>
</div>
<!-- container -->
<% else %>
<div id="eventslisting">
<%if Integer(@list) == 1 then%>
<h3>The gallery is empty.<br /><br/>We'll have some art up soon. </h3>
<% else %>
<h3>There is no artwork on this page </h3>
<% end %>
</div>
<% end %>

app/views/works/new.html.erb
<h1>New work</h1>
<div id="ArtistLeft">
<%= render 'form' %>
</div>
<%= link_to 'Back', works_path %>

app/views/works/permadm.html.erb
<div id="BodySurround"><h1>You must be the artist or an admin to do that </h1>
</div>

app/views/works/permission.html.erb
<div id="BodySurround"><h1>You must be an artist to do that. </h1>
</div>

app/views/works/show.html.erb
<ul id="artlist">
<li>


<div id="ArtLeft">

  <p id="notice"><%= notice %></p>
  <br />
  <b>Name:</b>
  <%= @work.name %>
  <br />
  <b>Artist:</b>
  <%= Artist.find(@work.artist_id).name %>
  <br />
  <b>Medium:</b>
  <%= @work.medium %>
  <br />
  <b>Date:</b>
  <%= @work.date %>
  <br />
  <b>Size:</b>
  <%= @work.size %>
  <br />
  <b>Status:</b>
  <%= @work.status %>
  <br />
  <b>Price (US Dollars):</b>
  <%= @work.price %>
  <br />
  <b>Seller:</b>
  <%= @work.seller %>
<br />
  <!-- <%= link_to 'Edit', edit_work_path(@work) %> | -->
  <%= link_to 'Back', works_path %>

</div>
</li>
<li>

<span id="ArtPic">
  <%= image_tag(@imgtag, :size => "#{@sizex}x#{@sizey}", :border => 5) %>
</span>

</li>
</ul>

app/views/works/show_artist.html.erb
<p id="notice"><%= notice %>
</p>

<% if Integer(@list) * @numperpage < @works.length then%>
   <% @max = Integer(@list) * @numperpage -1 %>
   <% else%>
   <% @max = (@works.length) -1 %>
   <% end%>
   <% @start = (Integer(@list)-1) * @numperpage%>
   <% unless @max < @start then %>
      <div id="PersonalListing">
	<%if @artist.nil? then %>
	<h3>The Artwork: page 
	  <span id="numberOverload"><%= @list%>
	    </span>
	  <br />
	</h3>
	<% else %>
	<h3><%= link_to(@artist.name, :controller => "artists", :action => "show", :id => @artid) %>'s Artwork: page 
	  <span id="numberOverload"><%= @list%></span>
	  <br />
	</h3>
	<%end%>
	<p id="bottom">

	  <% @count = @workcount / @numperpage + 1%>
	  <% unless @count == 1%>
	  <% for each in 1..@count%>
	  <%= link_to(each, :controller => "works", :action => "show_artist", :list => "#{each}", :id => @artid) %>
<% end%>
<% end%>
</p>
</div>

  <div class="out">
    <% (@start..@max).each do |index| %>
    <% @offset = index - @start %>
    <% if (@offset  == (@offset / @numperline) * @numperline ) then%>
    <% unless @locclose = 1%>
    <% @locclose = 1 %>
    <ul>
      <% else%>
    </ul>
    <ul>
      <% end %>
      <% end %>
      <li class="outer">
	<table class="nested">
	  <tr>
	    <td class="inner">
	      <div class="imageinstance">
	      <% @img = @works[index] %>
	      <span class="photo">
	    <%= link_to image_tag(@img.photo.url(:index)), @img %>
	    </span>
    <div id="tagger">        <%= @works[index].name %>
    <br/>by
    <% @linkname= @works[index].artist.name%>
    <% @linkpath = @works[index].artist %>
    <%= link_to @linkname, @linkpath%>
</div>
</div>

	    </td>
	  </tr>
	</table>
      </li>

      <% end %>
    </ul>
  </div>

<% else %>
<div id="PersonalListing">
<%if Integer(@list) == 1 then%>
<h3>This artist hasn't posted any of their work. </h3>
<%= link_to( "The Artist", :controller => "artists", :action => "show", :id => @artid) %>
<% else %>
<h3>There is no artwork on this page </h3>
<% end %>
</div>
<% end %>