config/routes.rb
ArtHouse::Application.routes.draw do
  resources :accounts do
    get :delete, :on => :member
    get :updater, :on => :member

    collection do
      get 'updater'
      get 'makeadmin'
      get 'makesuper'
      get 'list'
      get 'login'
      get 'logout'
      get 'permission'
      get 'changepassword'
    end
  end

  resources :events do
        get :delete, :on => :member
      end

  resources :works do
    get :delete, :on => :member
    collection do
      get 'show_artist'
    end
  end
  match "/works/show_artist/:id" => "works#show_artist"
  root :to => 'pages#about'
  resources :artists do
    get :delete, :on => :member
    collection do
    get :alumni
      end
  end
  get "pages/about"

  get "pages/contact"

  get "pages/bios"

  get "pages/gallery"

end

app/models/account.rb
class Account < ActiveRecord::Base
validates_length_of :username, :within => 3..40
  validates_length_of :password, :within => 5..40
  validates_presence_of :username, :password, :password_confirmation, :salt, :permission
  validates_uniqueness_of :username
  validates_confirmation_of :password
  validates_numericality_of :artist, :permission


  attr_protected :id, :salt
  attr_accessor :password, :password_confirmation

  def self.authenticate(username, pass)
    u=find(:first, :conditions=>["username = ?", username])
    return nil if u.nil?
    return u if Account.encrypt(pass, u.salt)==u.hashedpass
    nil
  end 

  def password=(pass)
    @password=pass
    self.salt = Account.random_string(10) if !self.salt?
    self.hashedpass = Account.encrypt(@password, self.salt)
  end

  # def update_attribute()
  #   unless password == pass_confirmation
  #     return false
  #   else
  #     false
  #   end
  # end
protected

  def self.encrypt(pass, salt)
    password = pass
    for i in 1..1000 do
      password = Digest::SHA256.hexdigest(password+salt)
    end
    password
  end

  def self.random_string(len)
    #generat a random password consisting of strings and digits
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    newpass = ""
    1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
    return newpass
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :set_env
  before_filter :auth
  def index
    @ident = authenticate("get_id")
  end

  def new
    @account = Account.new
    if authenticate("create")
      respond_to do |format|
       format.html
      end
    else
      respond_to do |format|
        format.html { render :action => 'permission' }
      end
    end    
  end

  def makeadmin
    @account = Account.find(params[:id])
    @permission = authenticate('makeadmin')
      unless @account.nil?
    if @permission and (@account.permission > -1) and (1 > @account.permission)
      
      @account.update_attribute(:permission, 1)
      respond_to do |format|
        format.html { redirect_to :action => 'list' }
      end
    else
      permalt
    end
  else
    permalt
  end
end
def makesuper
  @account = Account.find(params[:id])
  unless @account.nil?
    @permission = authenticate('makesuper')
    if @permission and (@account.permission > -1)
      @account.update_attribute(:permission, 2)
      respond_to do |format|
        format.html { redirect_to :action => 'index' }
      end
    else
      permalt
    end
  else
    permalt
  end
end

def changepassword
  @account = Account.find(params[:id])
  unless @account.nil?
    id = authenticate('get_id')
    if id == params[:id].to_i
      respond_to do |format|
        format.html
      end
    else
      permalt
    end
  else
    permalt
  end

end


  def updater
      @account = Account.find(params[:account])
    if authenticate("get_id").to_i == @account.id
        respond_to do |format|
          if @account.save
            format.html { redirect_to :action => "index" }
            flash[:message] = "Signup successful"
          else
            format.html { render :action => "new" }
            flash[:warning] = "Signup unsuccessful"
          end
        end
      else
        permalt
      end
    end

  def update
      @account = Account.find(params[:id])
      if true
        respond_to do |format|
          if @account.update_attributes(params[:account])
            format.html { redirect_to :action => "index" }
            flash[:message] = "Signup successful"
          else
            format.html { render :action => "changepassword" }
            flash[:warning] = "Signup unsuccessful"
          end
        end
      else
        permalt
      end
    end


    def create
      @account = Account.new(params[:account])
      if authenticate("create")
        respond_to do |format|
          if @account.save
            format.html { redirect_to :action => "index" }
            flash[:message] = "Signup successful"
          else
            format.html { render :action => "new" }
            flash[:warning] = "Signup unsuccessful"
          end
        end
      else
        permalt
      end
    end

    def login
      authenticate("login")
      respond_to do |format|
        format.html { render :action => "index" }
      end
    end

    def list
      if authenticate("list")
        @accounts = Account.find(:all)
      else
        permalt
      end
    end
  
    def delete

    end

    def permission

    end

    def destroy
      @permission = authenticate("delete")
      if @permission
        @account = Account.find(params[:id])
        @account.destroy
        respond_to do |format|
          format.html { redirect_to :action => 'list' }
        end
      else
        permalt
      end
    end

    def logout
      session[:username] = nil
      session[:passhash] = nil
      reset_session
      redirect_to("/pages/about", :notice => 'Logged out')
    end

    
    


    def set_env
      @banner = "banner.jpg"
    end
    

    protected

    def permalt
        respond_to do |format|
          format.html { render(:action => "permission") }
        end
    end


    def permissions(act, account)
      @permission = account.permission
      if @permission.nil?
        false
      else
        artist = account.artist
        case act
        when "create"
          if @permission > 0
            true
          else
              false
          end
        when "delete"
          if @permission > 1
            @permission
          else
            false
          end
        when "get_id"
          account.id
        when "login"
          true
        when "list"
          if @permission > 0
            true
          else
            false
          end
        when "makeadmin"
          if @permission > 0
            @permission
          else
            false
          end
        when "makesuper"
          if @permission > 1
            @permission
          else
            false
          end
       
        else
          false     
        end
      end
    end
    def auth
      authenticate("login")
    end
    def authenticate(action)
      @match = nil
      if (session[:username].nil? or session[:passhash].nil?)
        authenticate_or_request_with_http_basic do |user, password|
          @match= Account.find_by_username(user)


          passhash = "xxxxxxxxxx"
          unless @match.nil?
            passhash = Account.encrypt(password, @match.salt)
            if !(@match.hashedpass == passhash)
              @match = nil
            else
              session[:username] = user
              session[:passhash] = passhash
            end
          else
            @match = nil
            
          end
        end
        # above end authenticate_http
      else
        @match = Account.find_by_username(session[:username])
        unless @match.nil?
        if !(@match.hashedpass == session[:passhash])
          match = nil
        end
          end
      end
      

      if @match.nil?
        false
      else
        if action.nil?
          action= "login"
        end
        permissions(action, @match)
      end


    end

    def su?(permission)
      if permission == 2
        true
      else
        false
      end
    end
    def admin?(permission)
      if permission == 1 or permission == 2
        true
      else
        false
      end
    end
  end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/.#changepassword.html.erb
megaloman@ragebox.3009:1314909400

app/views/accounts/_editform.html.erb
<!--   <%= form_for @account, :url => { :action => "updater" } do |f| %> -->
<!--   <% if @account.errors.any? %> -->
<!--     <div id="error_explanation"> -->
<!--       <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2> -->

<!--       <ul> -->
<!--       <% @account.errors.full_messages.each do |msg| %> -->
<!--         <li><%= msg %></li> -->
<!--       <% end %> -->
<!--       </ul> -->
<!--     </div> -->
<!--   <% end %> -->

<!--   <div class="field"> -->
<!--     <%= f.label "New Password" %><br /> -->
<!--     <%= f.password_field :password %> -->
<!--   </div> -->
<!--     <div class="field"> -->
<!--     <%= f.label "New Password confirmation" %><br /> -->
<!--     <%= f.password_field :password_confirmation %> -->
<!--   </div> -->
<!--   <div class="actions"> -->
<!--     <%= f.submit %> -->
<!--   </div> -->
<!-- <% end %> -->



  <%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.hidden_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label "Password Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">

    <%= f.hidden_field :artist %>
  </div>
  <div class="field">

    <%= f.hidden_field :permission %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_form.html.erb
  <%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label "New Account Password" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label "New Password Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label "Artist id, found when viewing the artist: -1 if not created yet or not an artist" %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label "Permission: -1 for new artist, -2 for new artist that will administrate. 0 for existing artist. 1 for administrator. 2 for Super" %><br />
    <%= f.text_field :permission %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/changepassword.html.erb
<h1>Editing Password</h1>
<%= @permission %>
<br/>
<%= render 'editform' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Actions</h1>


<%= link_to 'New Account', new_account_path %>
<br />
<%= link_to 'List Accounts (Priviledged)', :action => 'list' %>
<%= link_to 'Change your password.', :controller => 'accounts', :action => 'changepassword', :id => @ident %>
<br />

app/views/accounts/list.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Artist</th>
    <th>Permission</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% unless @accounts.nil? %>
<% @accounts.each do |account| %>
  <tr>
    <td><%= account.username %></td>
    <td><%= account.artist %></td>
    <td><%= account.permission %></td>
    <td><%= link_to 'Make Super', :controller => "accounts", :action => 'makesuper', :id => account.id %></td>
    <td><%= link_to 'Make Admin', :controller => "accounts", :action => 'makeadmin', :id => account.id %></td>
    
    <td><%= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @account.username %>
</p>

<p>
  <b>Hashedpass:</b>
  <%= @account.hashedpass %>
</p>

<p>
  <b>Artist:</b>
  <%= @account.artist %>
</p>

<p>
  <b>Permission:</b>
  <%= @account.permission %>
</p>

<p>
  <b>Salt:</b>
  <%= @account.salt %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>